.PHONY: all

all:
	cd crypto && make
	cd crypto_nv && make
	cd ecryptfs && make
	cd file_io && make
	
clean:
	cd crypto && make clean
	cd crypto_nv && make clean
	cd ecryptfs && make clean
	cd file_io && make clean